### PR TITLE
Added get_API_infos(), comment management and workitem relation retreival

### PR DESCRIPTION
**Pull request by ColinChargyBentley**
Hi,
This fct allows to retrieve info from server regarding API and version supported. This is useful when developing to know what are is the API range to be used (for example, comment access by revision has been introduced in version 3.0, removed after version 5.0 and does not support updating or deleting comment; after version 5.0, comment are accessed by ID and can be updating and removed). This could be useful, in the future, to choose, at runtime, between different possible API endpoint, the best one available on the server.
Regards,
Colin
PS.: I'm still working on comment management.

### CODE REVIEW

**Comment by ColinChargyBentley** [comment]
Hi,
I've added the comment handling (get, create and destroy).
Regards,
Colin
PS.: I'm done making changes for now...

**Comment by ColinChargyBentley** [comment]
I'm also working on workitem attachment retrieving!
Regards,
Colin

**Comment by ColinChargyBentley** [comment]
Hi,
Finally, I've also added the workitem relation retrieval, which is useful because relations contains the workitem attachment.
Regards,
Colin

**Comment by ColinChargyBentley** [comment]
Hi,
Finally, I've also added the workitem relation retrieval, which is useful because relations contains the workitem attachment.
Regards,
Colin

**Comment by ColinChargyBentley** [comment]
Hi @rcoenmans,
I'm done making changes!
Regards,
Colin Chargy

**Comment by rcoenmans** [comment]
Thanks Colin, I'll have a look at the changes over the weekend and include them in a new release if all is well. 

Thanks for your help!

**Comment by ColinChargyBentley** [comment]
Hi,
I've added one last commit because a colleague of mine created his personal access token but we wouldn't have it work unless we specified the e-mail adress. We found this login/e-mail in the doc : https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=preview-page#q-how-can-i-use-a-pat-in-my-code .
Regards,
Colin

**Comment by ColinChargyBentley** [comment]
Hi @rcoenmans 
Did you have the time to look at the changes ?
Regards,
Colin

**Review by rcoenmans — APPROVED** [review]

**Pull request merged**
